

services:
  server:
    container_name: server
    build: ./django_app
    ports:
      - 7070:8080
    env_file: .env
    restart: "on-failure"
    # depends_on: 
    #   broker: 
    #     condition: service_started
    #   celery: 
    #     condition: service_started

  celery:
    container_name: celery
    build: ./celery
    env_file: .env
    restart: "on-failure"
    # depends_on: 
    #   broker: 
    #     condition: service_started
    # depends_on: 
    #   redis: 
    #     condition: service_started
